class AppConstants {
  static const String blankProfileImage =
      "https://images.nightcafe.studio//assets/profile.png?tr=w-640,c-at_max";
  static const String title = "title";
  static const String description = "description";
  static const String projectLink = "project_link";
  static const String imageUrl = "image_url";
  static const String state = "state";
  static const String city = "city";
  static const String pincode = "pincode";
  static const String street = "street";
  static const String github = "github";
  static const String instagram = "instagram";
  static const String linkedin = "linkedin";
  static const String twitter = "twitter";
  static const String users = "users";
  static const String email = "email";
  static const String about = "about";
  static const String address = "address";
  static const String profession = "profession";
  static const String userImage = "user_image";
  static const String projects = "projects";
  static const String fName = "f_name";
  static const String lName = "l_name";
  static const String contacts = "contacts";
  static const String techSkills = "tech_skills";
  static const String socialMediaLinks = "social_media_links";
  static const String chats = "chats";
  static const String messages = "messages";
  static const String createdOn = "created_on";
  static const String text = "text";
  static const String userId = "user_id";
  static const String userEmails = "user_emails";
  static const String userHandle = "user_handle";
}
